### ISSUE TITLE
todo features

### ISSUE THREAD

**Issue by ritalin** [ritalin/omelet#1]
* [ ] Document comment to annotation
    * param -> ParamAlt
    * return -> Returning
* [ ] SQL path shortcut
    * Add DAO Annotation
    * As annotation option, specifying shortcut path.
* [ ] Watching modification for SQL or DAO
    * add mode enumeration.
* [ ] Enhance errors checking.
* [ ] Supports any class as the entity
   * ignore Entity annotation ?
